server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  db:
    database: hm-trade
  swagger:
    title: 黑马商城订单接口文档
    desc: 黑马商城订单接口文档
    src: come.hm.trade.controller
spring:
  rabbitmq:
    host: 192.168.100.128 # 虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: rabbitmq # 用户名
    password: rabbitmq # 密码