server:
  port: 8084
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  db:
    database: hm-user
  swagger:
    title: 黑马商城用户接口文档
    desc: 黑马商城用户接口文档
    src: com.hmall.user.controller