server:
  port: 8086
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true
hm:
  db:
    database: hm-pay
  swagger:
    title: 黑马商城支付接口文档
    desc: 黑马商城支付接口文档
    src: come.hm.pay.controller
spring:
  rabbitmq:
    host: 192.168.100.128 # 虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机
    username: rabbitmq # 用户名
    password: rabbitmq # 密码