server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true # 开启feign对sentinel的支持
hm:
  db:
    database: hm-cart
  swagger:
    title: 黑马商城购物车接口文档
    desc: 黑马商城购物车接口文档
    src: come.hm.cart.controller
  cart:
    max-capacity: 10
spring:
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.100.128:8090
      http-method-specify: true